### ISSUE TITLE
np.float needs to be changed float due to deprecation in Numpy

### ISSUE THREAD

**Issue by JordanWean** [perslab/CELLEX#38]
Cellex uses np.float in the anova.py file which was deprecated in numpy 1.24. Changing np.float to just float seems to fix the issue.

**Comment by tstannius** [comment]
Hi Jordan

Thanks for your interest.

I do not currently have the time to prioritize addressing such requests and testing how it impacts the output. If anything, I would like to spend time on cellex v2 :-)

Nevertheless, it sounds like you have found a solution so that at least you are not stuck.

Alternatively I would recommend setting up a venv or conda env using the exact versions specified in the requirements.txt.


Best,
Tobi

**Comment by SCQUchenyang** [comment]
Thanks! I met the same error when I "import cellex". 
Find the script——”site-packages/cellex/preprocessing/anova.py“, and change "np.float=0.00001" to "float=0.00001" is right way.

**Comment by tstannius** [comment]
Thanks for confirming SCQUchenyang!

I will close this issue for now, as there are solution suggestions in this thread and cellex v2 is higher priority than fixes for v1.

Best,
Tobi

**Comment by mohamednhassan** [comment]
installing cellex
import cellex raised an error: 
/.local/lib/python3.8/site-packages/cellex/preprocessing/anova.py >> np.float >> float

2-
import loompy
import pandas as pd

with loompy.connect(pathData) as ds:
    # Use 'var_names' for gene names (row identifiers)
    rows = ds.row_attrs["var_names"]
    
    # Use 'obs_names' for cell IDs (column identifiers)
    cols = ds.col_attrs["obs_names"]
    
    # Expression matrix
    data = pd.DataFrame(ds[:, :], index=rows, columns=cols)
    
    # Use appropriate annotation columns — here are some options you might want:
    metadata = pd.DataFrame({
        "cell_type": ds.col_attrs["celltype"]  # or try 'annotation_heatmap' if more relevant
    }, index=cols)
    
    metadata_class = pd.DataFrame({
        "cell_class": ds.col_attrs["celltype2"]  # you can swap this with a more suitable one if needed
    }, index=cols)
